import {MD3LightTheme, MD3DarkTheme, configureFonts} from 'react-native-paper';

const fontConfig = {
  displayLarge: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 57,
    letterSpacing: 0,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 45,
    letterSpacing: 0,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 36,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headlineLarge: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 22,
    letterSpacing: 0,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: 'Roboto',
    fontWeight: '500' as const,
    fontSize: 16,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: 'Roboto',
    fontWeight: '500' as const,
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: 'Roboto',
    fontWeight: '500' as const,
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  labelMedium: {
    fontFamily: 'Roboto',
    fontWeight: '500' as const,
    fontSize: 12,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: 'Roboto',
    fontWeight: '500' as const,
    fontSize: 11,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  bodyLarge: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 14,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: 'Roboto',
    fontWeight: '400' as const,
    fontSize: 12,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
};

// Light theme colors matching the web app
export const lightTheme = {
  ...MD3LightTheme,
  fonts: configureFonts({config: fontConfig}),
  colors: {
    ...MD3LightTheme.colors,
    primary: '#1976d2',
    primaryContainer: '#bbdefb',
    secondary: '#9c27b0',
    secondaryContainer: '#e1bee7',
    tertiary: '#ff9800',
    tertiaryContainer: '#ffe0b2',
    surface: '#ffffff',
    surfaceVariant: '#f5f5f5',
    background: '#fafafa',
    error: '#d32f2f',
    errorContainer: '#ffcdd2',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#1565c0',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#7b1fa2',
    onTertiary: '#000000',
    onTertiaryContainer: '#e65100',
    onSurface: '#212121',
    onSurfaceVariant: '#757575',
    onBackground: '#212121',
    onError: '#ffffff',
    outline: '#bdbdbd',
    outlineVariant: '#e0e0e0',
    inverseSurface: '#303030',
    inverseOnSurface: '#ffffff',
    inversePrimary: '#90caf9',
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  roundness: 8,
};

// Dark theme colors matching the web app
export const darkTheme = {
  ...MD3DarkTheme,
  fonts: configureFonts({config: fontConfig}),
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#90caf9',
    primaryContainer: '#1565c0',
    secondary: '#ce93d8',
    secondaryContainer: '#7b1fa2',
    tertiary: '#ffb74d',
    tertiaryContainer: '#e65100',
    surface: '#121212',
    surfaceVariant: '#1e1e1e',
    background: '#121212',
    error: '#ef5350',
    errorContainer: '#b71c1c',
    onPrimary: '#000000',
    onPrimaryContainer: '#bbdefb',
    onSecondary: '#000000',
    onSecondaryContainer: '#e1bee7',
    onTertiary: '#000000',
    onTertiaryContainer: '#ffe0b2',
    onSurface: '#ffffff',
    onSurfaceVariant: '#bdbdbd',
    onBackground: '#ffffff',
    onError: '#000000',
    outline: '#616161',
    outlineVariant: '#424242',
    inverseSurface: '#ffffff',
    inverseOnSurface: '#000000',
    inversePrimary: '#1976d2',
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.7)',
  },
  roundness: 8,
};

// Default to light theme
export const theme = lightTheme;

export default theme;
