framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    rate_limiter:
        register:
            policy: 'fixed_window'
            limit: 3
            interval: '1 hour'
        refresh_token:
            policy: 'sliding_window'
            limit: 60
            interval: '1 minute'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
